// // ignore_for_file: must_be_immutable
// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';
// import 'package:media_alkafel_v2/app/controllers/auth_controller.dart';
// import 'package:media_alkafel_v2/app/views/widgets/input_text.dart';

// import '../../utils/constants/color_app.dart';
// import '../../utils/constants/style_app.dart';
// import '../../utils/constants/values_constant.dart';

// class DropdownContres extends StatelessWidget {
//   // تحديد اللغة المختارة حاليًا
//   String selectedLanguage = 'Arabic'; // الافتراضي هو اللغة العربية
//   AuthController authController = Get.find<AuthController>();
//   // تحديد الدولة المختارة حاليًا

//   // قائمة الدول مع الترجمات
//   final Map<String, Map<String, String>> countries = {
//     'Arabic': {
//       'AF': 'أفغانستان',
//       'AL': 'ألبانيا',
//       'DZ': 'الجزائر',
//       'AS': 'ساموا الأمريكية',
//       'AD': 'أندورا',
//       'AO': 'أنغولا',
//       'AI': 'أنغيلا',
//       'AQ': 'أنتاركتيكا',
//       'AG': 'أنتيغوا وباربودا',
//       'AR': 'الأرجنتين',
//       'AM': 'أرمينيا',
//       'AW': 'أروبا',
//       'AU': 'أستراليا',
//       'AT': 'النمسا',
//       'AZ': 'أذربيجان',
//       'BS': 'جزر البهاما',
//       'BH': 'البحرين',
//       'BD': 'بنغلاديش',
//       'BB': 'بربادوس',
//       'BY': 'بيلاروسيا',
//       'BE': 'بلجيكا',
//       'BZ': 'بليز',
//       'BJ': 'بنين',
//       'BM': 'برمودا',
//       'BT': 'بوتان',
//       'BO': 'بوليفيا',
//       'BA': 'البوسنة والهرسك',
//       'BW': 'بوتسوانا',
//       'BR': 'البرازيل',
//       'BN': 'بروناي',
//       'BG': 'بلغاريا',
//       'BF': 'بوركينا فاسو',
//       'BI': 'بوروندي',
//       'KH': 'كمبوديا',
//       'CM': 'الكاميرون',
//       'CA': 'كندا',
//       'CV': 'الرأس الأخضر',
//       'CF': 'جمهورية أفريقيا الوسطى',
//       'TD': 'تشاد',
//       'CL': 'تشيلي',
//       'CN': 'الصين',
//       'CO': 'كولومبيا',
//       'KM': 'جزر القمر',
//       'CG': 'الكونغو',
//       'CD': 'جمهورية الكونغو الديمقراطية',
//       'CR': 'كوستاريكا',
//       'CI': 'ساحل العاج',
//       'HR': 'كرواتيا',
//       'CU': 'كوبا',
//       'CY': 'قبرص',
//       'CZ': 'التشيك',
//       'DK': 'الدنمارك',
//       'DJ': 'جيبوتي',
//       'DM': 'دومينيكا',
//       'DO': 'جمهورية الدومينيكان',
//       'EC': 'الإكوادور',
//       'EG': 'مصر',
//       'SV': 'السلفادور',
//       'GQ': 'غينيا الاستوائية',
//       'ER': 'إريتريا',
//       'EE': 'إستونيا',
//       'ET': 'إثيوبيا',
//       'FJ': 'فيجي',
//       'FI': 'فنلندا',
//       'FR': 'فرنسا',
//       'GA': 'الجابون',
//       'GM': 'غامبيا',
//       'GE': 'جورجيا',
//       'DE': 'ألمانيا',
//       'GH': 'غانا',
//       'GR': 'اليونان',
//       'GD': 'غرينادا',
//       'GT': 'غواتيمالا',
//       'GN': 'غينيا',
//       'GW': 'غينيا بيساو',
//       'GY': 'غيانا',
//       'HT': 'هايتي',
//       'HN': 'هندوراس',
//       'HU': 'المجر',
//       'IS': 'آيسلندا',
//       'IN': 'الهند',
//       'ID': 'إندونيسيا',
//       'IR': 'إيران',
//       'IQ': 'العراق',
//       'IE': 'أيرلندا',
//       'IT': 'إيطاليا',
//       'JM': 'جامايكا',
//       'JP': 'اليابان',
//       'JO': 'الأردن',
//       'KZ': 'كازاخستان',
//       'KE': 'كينيا',
//       'KI': 'كيريباتي',
//       'KP': 'كوريا الشمالية',
//       'KR': 'كوريا الجنوبية',
//       'KW': 'الكويت',
//       'KG': 'قرغيزستان',
//       'LA': 'لاوس',
//       'LV': 'لاتفيا',
//       'LB': 'لبنان',
//       'LS': 'ليسوتو',
//       'LR': 'ليبيريا',
//       'LY': 'ليبيا',
//       'LI': 'ليختنشتاين',
//       'LT': 'ليتوانيا',
//       'LU': 'لوكسمبورغ',
//       'MG': 'مدغشقر',
//       'MW': 'مالاوي',
//       'MY': 'ماليزيا',
//       'MV': 'جزر المالديف',
//       'ML': 'مالي',
//       'MT': 'مالطا',
//       'MH': 'جزر مارشال',
//       'MQ': 'مارتينيك',
//       'MR': 'موريتانيا',
//       'MU': 'موريشيوس',
//       'MX': 'المكسيك',
//       'FM': 'ولايات ميكرونيزيا المتحدة',
//       'MD': 'مولدوفا',
//       'MC': 'موناكو',
//       'MN': 'منغوليا',
//       'ME': 'الجبل الأسود',
//       'MA': 'المغرب',
//       'MZ': 'موزمبيق',
//       'MM': 'ميانمار',
//       'NA': 'ناميبيا',
//       'NR': 'ناورو',
//       'NP': 'نيبال',
//       'NL': 'هولندا',
//       'NZ': 'نيوزيلندا',
//       'NI': 'نيكاراغوا',
//       'NE': 'النيجر',
//       'NG': 'نيجيريا',
//       'NO': 'النرويج',
//       'OM': 'عمان',
//       'PK': 'باكستان',
//       'PW': 'بالاو',
//       'PS': 'فلسطين',
//       'PA': 'بنما',
//       'PG': 'بابوا غينيا الجديدة',
//       'PY': 'باراغواي',
//       'PE': 'بيرو',
//       'PH': 'الفلبين',
//       'PL': 'بولندا',
//       'PT': 'البرتغال',
//       'QA': 'قطر',
//       'RO': 'رومانيا',
//       'RU': 'روسيا',
//       'RW': 'رواندا',
//       'SA': 'السعودية',
//       'SN': 'السنغال',
//       'RS': 'صربيا',
//       'SC': 'سيشل',
//       'SL': 'سيراليون',
//       'SG': 'سنغافورة',
//       'SK': 'سلوفاكيا',
//       'SI': 'سلوفينيا',
//       'SB': 'جزر سليمان',
//       'SO': 'الصومال',
//       'ZA': 'جنوب أفريقيا',
//       'ES': 'إسبانيا',
//       'LK': 'سريلانكا',
//       'SD': 'السودان',
//       'SR': 'سورينام',
//       'SE': 'السويد',
//       'CH': 'سويسرا',
//       'SY': 'سوريا',
//       'TW': 'تايوان',
//       'TJ': 'طاجيكستان',
//       'TZ': 'تنزانيا',
//       'TH': 'تايلاند',
//       'TL': 'تيمور الشرقية',
//       'TG': 'توغو',
//       'TO': 'تونغا',
//       'TT': 'ترينيداد وتوباغو',
//       'TN': 'تونس',
//       'TR': 'تركيا',
//       'TM': 'تركمانستان',
//       'TV': 'توفالو',
//       'UG': 'أوغندا',
//       'UA': 'أوكرانيا',
//       'AE': 'الإمارات العربية المتحدة',
//       'GB': 'المملكة المتحدة',
//       'US': 'الولايات المتحدة',
//       'UY': 'أورغواي',
//       'UZ': 'أوزبكستان',
//       'VU': 'فانواتو',
//       'VE': 'فنزويلا',
//       'VN': 'فيتنام',
//       'YE': 'اليمن',
//       'ZM': 'زامبيا',
//       'ZW': 'زيمبابوي',
//     },
//     'English': {
//       'AF': 'Afghanistan',
//       'AL': 'Albania',
//       'DZ': 'Algeria',
//       'AS': 'American Samoa',
//       'AD': 'Andorra',
//       'AO': 'Angola',
//       'AI': 'Anguilla',
//       'AQ': 'Antarctica',
//       'AG': 'Antigua and Barbuda',
//       'AR': 'Argentina',
//       'AM': 'Armenia',
//       'AW': 'Aruba',
//       'AU': 'Australia',
//       'AT': 'Austria',
//       'AZ': 'Azerbaijan',
//       'BS': 'Bahamas',
//       'BH': 'Bahrain',
//       'BD': 'Bangladesh',
//       'BB': 'Barbados',
//       'BY': 'Belarus',
//       'BE': 'Belgium',
//       'BZ': 'Belize',
//       'BJ': 'Benin',
//       'BM': 'Bermuda',
//       'BT': 'Bhutan',
//       'BO': 'Bolivia',
//       'BA': 'Bosnia and Herzegovina',
//       'BW': 'Botswana',
//       'BR': 'Brazil',
//       'BN': 'Brunei',
//       'BG': 'Bulgaria',
//       'BF': 'Burkina Faso',
//       'BI': 'Burundi',
//       'KH': 'Cambodia',
//       'CM': 'Cameroon',
//       'CA': 'Canada',
//       'CV': 'Cape Verde',
//       'CF': 'Central African Republic',
//       'TD': 'Chad',
//       'CL': 'Chile',
//       'CN': 'China',
//       'CO': 'Colombia',
//       'KM': 'Comoros',
//       'CG': 'Congo',
//       'CD': 'Democratic Republic of the Congo',
//       'CR': 'Costa Rica',
//       'CI': 'Côte d\'Ivoire',
//       'HR': 'Croatia',
//       'CU': 'Cuba',
//       'CY': 'Cyprus',
//       'CZ': 'Czech Republic',
//       'DK': 'Denmark',
//       'DJ': 'Djibouti',
//       'DM': 'Dominica',
//       'DO': 'Dominican Republic',
//       'EC': 'Ecuador',
//       'EG': 'Egypt',
//       'SV': 'El Salvador',
//       'GQ': 'Equatorial Guinea',
//       'ER': 'Eritrea',
//       'EE': 'Estonia',
//       'ET': 'Ethiopia',
//       'FJ': 'Fiji',
//       'FI': 'Finland',
//       'FR': 'France',
//       'GA': 'Gabon',
//       'GM': 'Gambia',
//       'GE': 'Georgia',
//       'DE': 'Germany',
//       'GH': 'Ghana',
//       'GR': 'Greece',
//       'GD': 'Grenada',
//       'GT': 'Guatemala',
//       'GN': 'Guinea',
//       'GW': 'Guinea-Bissau',
//       'GY': 'Guyana',
//       'HT': 'Haiti',
//       'HN': 'Honduras',
//       'HU': 'Hungary',
//       'IS': 'Iceland',
//       'IN': 'India',
//       'ID': 'Indonesia',
//       'IR': 'Iran',
//       'IQ': 'Iraq',
//       'IE': 'Ireland',
//       'IT': 'Italy',
//       'JM': 'Jamaica',
//       'JP': 'Japan',
//       'JO': 'Jordan',
//       'KZ': 'Kazakhstan',
//       'KE': 'Kenya',
//       'KI': 'Kiribati',
//       'KP': 'North Korea',
//       'KR': 'South Korea',
//       'KW': 'Kuwait',
//       'KG': 'Kyrgyzstan',
//       'LA': 'Laos',
//       'LV': 'Latvia',
//       'LB': 'Lebanon',
//       'LS': 'Lesotho',
//       'LR': 'Liberia',
//       'LY': 'Libya',
//       'LI': 'Liechtenstein',
//       'LT': 'Lithuania',
//       'LU': 'Luxembourg',
//       'MG': 'Madagascar',
//       'MW': 'Malawi',
//       'MY': 'Malaysia',
//       'MV': 'Maldives',
//       'ML': 'Mali',
//       'MT': 'Malta',
//       'MH': 'Marshall Islands',
//       'MQ': 'Martinique',
//       'MR': 'Mauritania',
//       'MU': 'Mauritius',
//       'MX': 'Mexico',
//       'FM': 'Micronesia',
//       'MD': 'Moldova',
//       'MC': 'Monaco',
//       'MN': 'Mongolia',
//       'ME': 'Montenegro',
//       'MA': 'Morocco',
//       'MZ': 'Mozambique',
//       'MM': 'Myanmar',
//       'NA': 'Namibia',
//       'NR': 'Nauru',
//       'NP': 'Nepal',
//       'NL': 'Netherlands',
//       'NZ': 'New Zealand',
//       'NI': 'Nicaragua',
//       'NE': 'Niger',
//       'NG': 'Nigeria',
//       'NO': 'Norway',
//       'OM': 'Oman',
//       'PK': 'Pakistan',
//       'PW': 'Palau',
//       'PS': 'Palestine',
//       'PA': 'Panama',
//       'PG': 'Papua New Guinea',
//       'PY': 'Paraguay',
//       'PE': 'Peru',
//       'PH': 'Philippines',
//       'PL': 'Poland',
//       'PT': 'Portugal',
//       'QA': 'Qatar',
//       'RO': 'Romania',
//       'RU': 'Russia',
//       'RW': 'Rwanda',
//       'SA': 'Saudi Arabia',
//       'SN': 'Senegal',
//       'RS': 'Serbia',
//       'SC': 'Seychelles',
//       'SL': 'Sierra Leone',
//       'SG': 'Singapore',
//       'SK': 'Slovakia',
//       'SI': 'Slovenia',
//       'SB': 'Solomon Islands',
//       'SO': 'Somalia',
//       'ZA': 'South Africa',
//       'ES': 'Spain',
//       'LK': 'Sri Lanka',
//       'SD': 'Sudan',
//       'SR': 'Suriname',
//       'SE': 'Sweden',
//       'CH': 'Switzerland',
//       'SY': 'Syria',
//       'TW': 'Taiwan',
//       'TJ': 'Tajikistan',
//       'TZ': 'Tanzania',
//       'TH': 'Thailand',
//       'TL': 'Timor-Leste',
//       'TG': 'Togo',
//       'TO': 'Tonga',
//       'TT': 'Trinidad and Tobago',
//       'TN': 'Tunisia',
//       'TR': 'Turkey',
//       'TM': 'Turkmenistan',
//       'TV': 'Tuvalu',
//       'UG': 'Uganda',
//       'UA': 'Ukraine',
//       'AE': 'United Arab Emirates',
//       'GB': 'United Kingdom',
//       'US': 'United States',
//       'UY': 'Uruguay',
//       'UZ': 'Uzbekistan',
//       'VU': 'Vanuatu',
//       'VE': 'Venezuela',
//       'VN': 'Vietnam',
//       'YE': 'Yemen',
//       'ZM': 'Zambia',
//       'ZW': 'Zimbabwe',
//     },
//     'Farsi': {
//       'AF': 'افغانستان',
//       'AL': 'آلبانی',
//       'DZ': 'الجزایر',
//       'AS': 'ساموآی آمریکا',
//       'AD': 'آندورا',
//       'AO': 'آنگولا',
//       'AI': 'آنگویلا',
//       'AQ': 'قطب جنوب',
//       'AG': 'آنتیگوا و باربودا',
//       'AR': 'آرژانتین',
//       'AM': 'ارمنستان',
//       'AW': 'آروبا',
//       'AU': 'استرالیا',
//       'AT': 'اتریش',
//       'AZ': 'جمهوری آذربایجان',
//       'BS': 'باهاما',
//       'BH': 'بحرین',
//       'BD': 'بنگلادش',
//       'BB': 'باربادوس',
//       'BY': 'بلاروس',
//       'BE': 'بلژیک',
//       'BZ': 'بلیز',
//       'BJ': 'بنین',
//       'BM': 'برمودا',
//       'BT': 'بوتان',
//       'BO': 'بولیوی',
//       'BA': 'بوسنی و هرزگوین',
//       'BW': 'بوتسوانا',
//       'BR': 'برزیل',
//       'BN': 'برونئی',
//       'BG': 'بلغارستان',
//       'BF': 'بورکینافاسو',
//       'BI': 'بوروندی',
//       'KH': 'کامبوج',
//       'CM': 'کامرون',
//       'CA': 'کانادا',
//       'CV': 'کیپ ورد',
//       'CF': 'جمهوری آفریقای مرکزی',
//       'TD': 'چاد',
//       'CL': 'شیلی',
//       'CN': 'چین',
//       'CO': 'کلمبیا',
//       'KM': 'کومور',
//       'CG': 'کنگو',
//       'CD': 'جمهوری دموکراتیک کنگو',
//       'CR': 'کاستاریکا',
//       'CI': 'ساحل عاج',
//       'HR': 'کرواسی',
//       'CU': 'کوبا',
//       'CY': 'قبرس',
//       'CZ': 'جمهوری چک',
//       'DK': 'دانمارک',
//       'DJ': 'جیبوتی',
//       'DM': 'دومینیکا',
//       'DO': 'جمهوری دومینیکن',
//       'EC': 'اکوادور',
//       'EG': 'مصر',
//       'SV': 'السالوادور',
//       'GQ': 'گینه استوایی',
//       'ER': 'اریتره',
//       'EE': 'استونی',
//       'ET': 'اتیوپی',
//       'FJ': 'فیجی',
//       'FI': 'فنلاند',
//       'FR': 'فرانسه',
//       'GA': 'گابون',
//       'GM': 'گامبیا',
//       'GE': 'گرجستان',
//       'DE': 'آلمان',
//       'GH': 'غنا',
//       'GR': 'یونان',
//       'GD': 'گرنادا',
//       'GT': 'گواتمالا',
//       'GN': 'گینه',
//       'GW': 'گینه بیسائو',
//       'GY': 'گویان',
//       'HT': 'هائیتی',
//       'HN': 'هندوراس',
//       'HU': 'مجارستان',
//       'IS': 'ایسلند',
//       'IN': 'هند',
//       'ID': 'اندونزی',
//       'IR': 'ایران',
//       'IQ': 'عراق',
//       'IE': 'ایرلند',
//       'IT': 'ایتالیا',
//       'JM': 'جامائیکا',
//       'JP': 'ژاپن',
//       'JO': 'اردن',
//       'KZ': 'قزاقستان',
//       'KE': 'کنیا',
//       'KI': 'کیریباتی',
//       'KP': 'کره شمالی',
//       'KR': 'کره جنوبی',
//       'KW': 'کویت',
//       'KG': 'قرقیزستان',
//       'LA': 'لائوس',
//       'LV': 'لتونی',
//       'LB': 'لبنان',
//       'LS': 'لسوتو',
//       'LR': 'لیبریا',
//       'LY': 'لیبی',
//       'LI': 'لیختن‌اشتاین',
//       'LT': 'لیتوانی',
//       'LU': 'لوکزامبورگ',
//       'MG': 'ماداگاسکار',
//       'MW': 'مالاوی',
//       'MY': 'مالزی',
//       'MV': 'مالدیو',
//       'ML': 'مالی',
//       'MT': 'مالت',
//       'MH': 'جزایر مارشال',
//       'MQ': 'مارتینیک',
//       'MR': 'موریتانی',
//       'MU': 'موریس',
//       'MX': 'مکزیک',
//       'FM': 'میکرونزی',
//       'MD': 'مولداوی',
//       'MC': 'موناکو',
//       'MN': 'مغولستان',
//       'ME': 'مونته‌نگرو',
//       'MA': 'مراکش',
//       'MZ': 'موزامبیک',
//       'MM': 'میانمار',
//       'NA': 'نامیبیا',
//       'NR': 'نائورو',
//       'NP': 'نپال',
//       'NL': 'هلند',
//       'NZ': 'نیوزیلند',
//       'NI': 'نیکاراگوئه',
//       'NE': 'نیجر',
//       'NG': 'نیجریه',
//       'NO': 'نروژ',
//       'OM': 'عمان',
//       'PK': 'پاکستان',
//       'PW': 'پالائو',
//       'PS': 'فلسطین',
//       'PA': 'پاناما',
//       'PG': 'پاپوآ گینه نو',
//       'PY': 'پاراگوئه',
//       'PE': 'پرو',
//       'PH': 'فیلیپین',
//       'PL': 'لهستان',
//       'PT': 'پرتغال',
//       'QA': 'قطر',
//       'RO': 'رومانی',
//       'RU': 'روسیه',
//       'RW': 'رواندا',
//       'SA': 'عربستان سعودی',
//       'SN': 'سنگال',
//       'RS': 'صربستان',
//       'SC': 'سیشل',
//       'SL': 'سیرالئون',
//       'SG': 'سنگاپور',
//       'SK': 'اسلواکی',
//       'SI': 'اسلوونی',
//       'SB': 'جزایر سلیمان',
//       'SO': 'سومالی',
//       'ZA': 'آفریقای جنوبی',
//       'ES': 'اسپانیا',
//       'LK': 'سری‌لانکا',
//       'SD': 'سودان',
//       'SR': 'سورینام',
//       'SE': 'سوئد',
//       'CH': 'سوئیس',
//       'SY': 'سوریه',
//       'TW': 'تایوان',
//       'TJ': 'تاجیکستان',
//       'TZ': 'تانزانیا',
//       'TH': 'تایلند',
//       'TL': 'تیمور شرقی',
//       'TG': 'توگو',
//       'TO': 'تونگا',
//       'TT': 'ترینیداد و توباگو',
//       'TN': 'تونس',
//       'TR': 'ترکیه',
//       'TM': 'ترکمنستان',
//       'TV': 'تووالو',
//       'UG': 'اوگاندا',
//       'UA': 'اوکراین',
//       'AE': 'امارات متحده عربی',
//       'GB': 'بریتانیا',
//       'US': 'ایالات متحده آمریکا',
//       'UY': 'اروگوئه',
//       'UZ': 'ازبکستان',
//       'VU': 'وانواتو',
//       'VE': 'ونزوئلا',
//       'VN': 'ویتنام',
//       'YE': 'یمن',
//       'ZM': 'زامبیا',
//       'ZW': 'زیمبابوه',
//     },
//   };

//   @override
//   Widget build(BuildContext context) {
//     return GestureDetector(
//       onTap: () {
//         _showCountrySelectionSheet();
//       },
//       child: Obx(() {
//         return Container(
//           margin: const EdgeInsets.symmetric(horizontal: 5),
//           height: 54,
//           decoration: BoxDecoration(
//               color: ColorApp.whiteColor,
//               border: Border.all(
//                 color: ColorApp.subColor.withAlpha(150),
//                 width: 0.5,
//               ),
//               borderRadius: BorderRadius.circular(Values.circle)),
//           child: InputDecorator(
//             decoration: InputDecoration(
//               prefixIcon: Icon(
//                 CupertinoIcons.globe,
//                 color: ColorApp.textSecondryColor,
//               ),
//               enabledBorder: OutlineInputBorder(
//                   borderSide: BorderSide(
//                     color: ColorApp.subColor.withAlpha(150),
//                     width: 0.5,
//                   ),
//                   borderRadius: BorderRadius.circular(Values.circle)),
//               focusedBorder: OutlineInputBorder(
//                   borderSide: BorderSide(
//                     color: ColorApp.greenColor.withAlpha(150),
//                     width: 0.5,
//                   ),
//                   borderRadius: BorderRadius.circular(Values.circle)),
//               border: OutlineInputBorder(
//                 borderRadius: BorderRadius.circular(Values.circle),
//               ),
//               filled: true,
//               fillColor: ColorApp.whiteColor,
//               label: Container(
//                 padding:
//                     const EdgeInsets.symmetric(horizontal: 15, vertical: 5),
//                 child: Text(
//                   'اختر الجنسية',
//                   style:
//                       StringStyle.textTable.copyWith(color: ColorApp.subColor),
//                 ),
//               ),
//             ),
//             child: Row(
//               mainAxisAlignment: MainAxisAlignment.spaceBetween,
//               children: [
//                 Text(
//                     authController.selectedCountry.value!.isNotEmpty
//                         ? authController.selectedCountry.value!
//                         : 'اختر الجنسية',
//                     style: StringStyle.textLabil),
//                 const Icon(Icons.arrow_drop_down, color: Colors.grey),
//               ],
//             ),
//           ),
//         );
//       }),
//     );
//   }

//   Rx<TextEditingController> controllerContry = Rx(TextEditingController());
//   RxList<String> filteredKeys = <String>[].obs;

//   DropdownContres({super.key});

//   void _showCountrySelectionSheet() {
//     filteredKeys.assignAll(
//         countries[selectedLanguage]!.values); // تعيين القائمة الأصلية عند الفتح

//     showModalBottomSheet(
//         enableDrag: true,
//         sheetAnimationStyle: AnimationStyle(
//             curve: Curves.bounceIn, duration: Duration(milliseconds: 300)),
//         context: Get.context!,
//         shape: RoundedRectangleBorder(
//           borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
//         ),
//         builder: (context) {
//           return Container(
//               padding: const EdgeInsets.all(16),
//               child: Column(mainAxisSize: MainAxisSize.min, children: [
//                 Text('اختر الجنسية', style: StringStyle.textTable),
//                 const SizedBox(height: 10),
//                 InputText.inputStringValidatorIcon(
//                     w: Values.width,
//                     icon: CupertinoIcons.globe,
//                     'بحث',
//                     controllerContry.value,
//                     maxLine: 1,
//                     validator: (v) => null,
//                     onChanged: (value) {
//                       filteredKeys.assignAll(
//                         countries[selectedLanguage]!.values.where((country) =>
//                             country
//                                 .toLowerCase()
//                                 .contains(value!.toLowerCase())),
//                       );
//                       return null;
//                     }),
//                 Expanded(child: Obx(() {
//                   return ListView.builder(
//                       itemCount: filteredKeys.length,
//                       itemBuilder: (context, index) {
//                         String country = filteredKeys[index];
//                         return ListTile(
//                             title: Text(country),
//                             onTap: () {
//                               authController.selectedCountry.value = country;
//                               Get.backLegacy();
//                             });
//                       });
//                 }))
//               ]));
//         });
//   }
// }
